### ISSUE TITLE
Fix the whitespace css

### ISSUE THREAD

**Issue by kossel** [oms-tech/reviews#26]
**What feature would you like to see added?**
First appreciated doing this! Spaces that are added in reviews are not handled on the new review page. it looks like this:

![image](https://user-images.githubusercontent.com/1760498/181122732-ebc5385f-692b-461a-88ba-14d7d49e092d.png)

The fix is easy, just need to add `white-space: pre-wrap` CSS to the container div.  Since you are using Tailwind you can just add `whitespace-pre-wrap` class to [this line](https://github.com/oms-tech/reviews/blob/main/pages/courses/%5BcourseCode%5D/reviews.tsx#L113) 

PS:
I could've open a PR but it still missing proper dev/contribution documentation, also seems this repo doesn't accept public PRs

**Additional context**
after fix:
![image](https://user-images.githubusercontent.com/1760498/181123178-b9822f37-7ee6-4ec3-ac98-f89ca3f27f7c.png)

**Comment by m4ttsch** [comment]
Hey! Thanks for adding.

I think the larger feature here is that these reviews have markdown content in them, which ideally I would like to parse using something like [React Markdown](https://github.com/remarkjs/react-markdown). That way, I would get headers from "##", lists from "-" and italics from "_".

If you are interested, I would very much welcome a PR that adds the full markdown functionality. You should be able to fork and then open up a PR against the repo, but let me know if you have issues. 

Right now, my main focus is adding reviews in a simple, authenticated, identifiable manner.

**Comment by kossel** [comment]
Hi

I agree to parse the md format is definitely a better idea, but that might take longer. I just wanted to provide a quick fix (probably takes 1 min for you)  to make it readable right the way. 

 I am not sure about the future of this project nor your plan, but if your intention is to make it open sourced or community based probably you could add quick dev documentation. 

I cloned the repo but it won't run because `Sanity config not found`.

**Comment by m4ttsch** [comment]
@kossel Take a look at the PR (and site preview) above. Let me know your thoughts...

**Comment by kossel** [comment]
@m4ttsch Hi, thanks for knocking down this so quickly!! the PR seems fairly straightforward, I don't have any concerns.

**Comment by m4ttsch** [comment]
Merged!
