### ISSUE TITLE
[FEATURE REQUEST] See all recent reviews

### ISSUE THREAD

**Issue by annabkr** [oms-tech/reviews#38]
**What feature would you like to see added?**
A view that shows the newest reviews, across all courses. It was one of the features I used the most on the previous site.

Thanks for listening! 😄

**Comment by m4ttsch** [comment]
Oh interesting! Should be easy enough to build. So you prefer scrolling through most recent reviews instead of / ahead of drilling down on a particular course?

**Comment by annabkr** [comment]
Yes! 😄  Recent reviews give somewhat of a `"live"` view of a given semester, as the reviews start pouring in.
 
I will drill down into specific courses when I'm in the final decision making phase, but in the past being able to see recent reviews has helped me to stay up-to-date with what's happening around OMSCS and consider classes I wouldn't have otherwise considered.

**Comment by annabkr** [comment]
That would work. The dedicated page with N reviews in descending chronological order is really what I'm missing the most, so I'm hesitant to encourage scope creep 😉 but this would be cool if it's not too much additional work 😄

**Comment by m4ttsch** [comment]
Hey! Just finished this (#55). Right now, you can view the 100 most recent reviews [here](omscentral.com/reviews/recent). I'd like to adapt this to have infinite scroll, but I have to refresh my brain on how Intersection Observer works :)

LMK if this looks and/or if you want me to build anything else!

**Comment by annabkr** [comment]
Yay thank you @m4ttsch!
