### ISSUE TITLE
[FEATURE REQUEST] Add course metrics summary to course page

### ISSUE THREAD

**Issue by edgriebel** [oms-tech/reviews#73]
**What feature would you like to see added?**
I'd like to see metrics averages for Rating, Difficulty, Workload, and Reviews on a course detail page. For instance, looking at https://www.omscentral.com/courses/statistical-modeling-and-regression-analysis/reviews, if I wanted to know these values I could scroll down through the reviews and make an estimate or go back to https://www.omscentral.com/ and search for the course to get exact figures

**Additional context**
Course Page without metrics
<img width="1164" alt="Screen Shot 2022-11-11 at 8 36 17 AM" src="https://user-images.githubusercontent.com/205766/201353635-3f42b621-3dad-4599-82d7-3e489d3a75c0.png">

Homepage with metrics
<img width="1078" alt="Screen Shot 2022-11-11 at 8 36 54 AM" src="https://user-images.githubusercontent.com/205766/201353662-55393347-e4b4-4293-84fb-7d0d46ed3bdb.png">

**Comment by m4ttsch** [comment]
Fixed [here](https://github.com/oms-tech/reviews/commit/ff2d5ff82d52e9e028082231d70c4a2f99c9e502) thanks!
