### ISSUE TITLE
[EDIT] All Individual Course Review Pages

### ISSUE THREAD

**Issue by tedhartnell** [oms-tech/reviews#74]
**What information is incorrect or missing?**

The overall summary statistics for each course should be included on the individual course pages and not just on the home page:
* Rating
* Difficulty
* Workload
* Reviews

**Comment by m4ttsch** [comment]
Fixed [here](https://github.com/oms-tech/reviews/commit/ff2d5ff82d52e9e028082231d70c4a2f99c9e502) thanks!
