### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by blankdean** [oms-tech/reviews#75]
**What feature would you like to see added?**
After clicking on a course to see reviews, I not only want to see reviews, but I'd also like to see a summary of the reviews (avg difficulty, rating, etc). Right now, the review page of each course does not have summary data. The previous OMSCScentral had this and I found it helpful.

**Additional context**

**Comment by m4ttsch** [comment]
Fixed [here](https://github.com/oms-tech/reviews/commit/ff2d5ff82d52e9e028082231d70c4a2f99c9e502) thanks!
