### ISSUE TITLE
[BUG REPORT] Can't search by class shortcode

### ISSUE THREAD

**Issue by loganwishartcraig** [oms-tech/reviews#77]
**Describe the bug**
Per the placeholder text on the reviews page, I tried searching for "HPCA", but no results are found.

I'd expect short-code to be considered in search - or the placeholder text to be updated.

**To Reproduce**

1. Navigate to the home page
2. Search "HPCA" in the filter textbox.

**Expected behavior**
The course "High-Performance Computer Architecture" should appear as the first result.

**Screenshots**
![image](https://user-images.githubusercontent.com/7434537/210159498-cc66f4a5-0191-4f40-a258-276e13e0c738.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox

**Smartphone (please complete the following information):**
NA

**Additional context**
Searching for corse codes (e.g. "CSE-6220" or "6220") also produces unexpected results.

**Comment by loganwishartcraig** [comment]
Would love to open a PR for this myself, but I can't get local development working per https://github.com/oms-tech/reviews/discussions/64#discussioncomment-4563309

**Comment by m4ttsch** [comment]
Good catch, this is fixed, [here](https://github.com/oms-tech/reviews/commit/c455dfde531842095394b56b723f40daee35ae86)
