### ISSUE TITLE
[BUG REPORT] Missing ANLP

### ISSUE THREAD

**Issue by fj5891** [oms-tech/reviews#82]
New class from last semester ANLP (CSE 8803) has not been added for reviews (its an OMSA only class at this stage I believe)

**Comment by m4ttsch** [comment]
Thanks. Will Add!

**Comment by m4ttsch** [comment]
@fj5891 Can you provide me a syllabus and some textbook info for this course?

**Comment by fj5891** [comment]
Syllabus: https://mahdi-roozbahani.github.io/ANLP-Summer23/

There is no textbook as per the syllabus.

**Comment by fj5891** [comment]
@m4ttsch Any chance we can get the class added?

Would be great if we could get some reviews on the class before phase II registration opens!

**Comment by sc250024** [comment]
> Would be great if we could get some reviews on the class before phase II registration opens!

100% agreed!

**Comment by fj5891** [comment]
It actually looks like there are 2 new classes. ANLP for OMSA (started Spring 23), and NLP for OMSCS (started summer 2023).

Both should be added separately
CSE8803: ANLP:  https://mahdi-roozbahani.github.io/ANLP-Summer23/ 

CS7650: NLP: https://omscs.gatech.edu/cs-7650-natural-language-processing

**Comment by m4ttsch** [comment]
Added [here](https://www.omscentral.com/courses/special-topics-applied-natural-language-processing/reviews) thanks ⭐

**Comment by fj5891** [comment]
Great. Thanks. Looks like you can now add reviews for these classes by going to New Review.

One issue: On the home page, they do not appear under lists of courses, and also not when you search for them. Im presuming in the Search Courses box. Ideally they should appear with 0 reviews, and ratings of "-", difficulty "-"
