### ISSUE TITLE
Missing class: NLP

### ISSUE THREAD

**Issue by logic-tonic** [oms-tech/reviews#83]
**Describe the bug**
You cannot add a review for [NLP](https://omscs.gatech.edu/cs-7650-natural-language-processing)

**To Reproduce**

1. Go to "Add a Review"
2. Try adding a review for NLP

**Expected behavior**
You can add a review for NLP

**Comment by m4ttsch** [comment]
@logic-tonic can you provide me the name/code/syllabus/textbooks/hours for this course so I can add it?

**Comment by logic-tonic** [comment]
@m4ttsch the only info I have is what's listed on the course site: https://omscs.gatech.edu/cs-7650-natural-language-processing

**Comment by m4ttsch** [comment]
Added! Thanks ⭐

**Comment by m4ttsch** [comment]
https://www.omscentral.com/courses/natural-language-processing/reviews
