### ISSUE TITLE
"Mobile and Ubiquitous Computing" showing the wrong # reviews

### ISSUE THREAD

**Issue by logic-tonic** [oms-tech/reviews#86]
**Describe the bug**
The "Mobile and Ubiquitous Computing" class shows up as having 3 reviews, but when you click on the class page, it shows more than three reviews.

**Comment by m4ttsch** [comment]
Thank you. Had a synchronization error. This should be updated now. Thanks!

**Comment by logic-tonic** [comment]
Thank you!
