### ISSUE TITLE
Reviews missing from corresponding class page

### ISSUE THREAD

**Issue by westim** [oms-tech/reviews#87]
**Describe the bug**

Some classes have reviews which can be seen in the list of most recent reviews but are not present on the class-specific page of the website.

This doesn't seem to apply to all classes. I observed the issue for GA and ML reviews.

**To Reproduce**

1. Go to the [recent reviews](https://www.omscentral.com/reviews/recent)
2. Find the most recent review for Introduction to Graduate Algorithms
3. Navigate to the [Introduction to Graduate Algorithms review page](https://www.omscentral.com/courses/introduction-to-graduate-algorithms/reviews)
4. Compare the most recent reviews

**Expected behavior**

The same reviews should be visible on both pages.

**Comment by m4ttsch** [comment]
Thanks for the headsup. I just kicked off a redeploy and I am seeing the latest reviews on GA!
